# Generated by Django 5.0 on 2025-11-28 04:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリ名')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順序')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(max_length=50, unique=True, verbose_name='セッションコード')),
                ('party_size', models.IntegerField(verbose_name='来店人数')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Chat ID')),
                ('status', models.CharField(choices=[('active', '来店中'), ('calling_staff', '店員呼び出し中'), ('payment_requested', '会計依頼中'), ('completed', '完了'), ('cancelled', 'キャンセル')], default='active', max_length=20, verbose_name='ステータス')),
                ('started_at', models.DateTimeField(verbose_name='来店日時')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='退店日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'セッション',
                'verbose_name_plural': 'セッション',
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店舗名')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='住所')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('business_hours', models.TextField(blank=True, help_text='JSON形式', null=True, verbose_name='営業時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='営業中フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '店舗',
                'verbose_name_plural': '店舗',
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', '管理者'), ('chef', '料理人'), ('supervisor', 'スーパーバイザ'), ('staff', 'スタッフ')], max_length=20, verbose_name='役割')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最終ログイン日時')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='価格')),
                ('image_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='商品画像ファイルパス')),
                ('image_thumbnail_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='サムネイル画像パス')),
                ('max_quantity_per_order', models.IntegerField(blank=True, default=10, null=True, verbose_name='1注文あたりの最大数量')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順序')),
                ('is_available', models.BooleanField(default=True, help_text='売り切れ管理', verbose_name='提供可能フラグ')),
                ('is_active', models.BooleanField(default=True, help_text='メニュー削除', verbose_name='有効フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.category', verbose_name='カテゴリ')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': 'メニュー項目',
                'verbose_name_plural': 'メニュー項目',
                'db_table': 'menu_item',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram User ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Username')),
                ('order_number', models.IntegerField(verbose_name='注文番号')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='合計金額')),
                ('status', models.CharField(choices=[('pending', '注文受付済み'), ('cooking', '調理中'), ('ready', '調理完了'), ('served', '提供済み'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='ステータス')),
                ('ordered_at', models.DateTimeField(verbose_name='注文日時')),
                ('cooking_started_at', models.DateTimeField(blank=True, null=True, verbose_name='調理開始日時')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='調理完了日時')),
                ('served_at', models.DateTimeField(blank=True, null=True, verbose_name='提供日時')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='キャンセル日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='キャンセル実行者')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.session', verbose_name='セッション')),
            ],
            options={
                'verbose_name': '注文',
                'verbose_name_plural': '注文',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='StaffCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('water', 'お水が欲しい'), ('payment', '会計したい'), ('question', '質問がある'), ('complaint', '苦情・問題'), ('other', 'その他')], max_length=20, verbose_name='理由')),
                ('message', models.TextField(blank=True, null=True, verbose_name='メッセージ')),
                ('status', models.CharField(choices=[('pending', '未対応'), ('in_progress', '対応中'), ('resolved', '解決済み')], default='pending', max_length=20, verbose_name='ステータス')),
                ('called_at', models.DateTimeField(verbose_name='呼び出し日時')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='対応開始日時')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解決日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.session', verbose_name='セッション')),
            ],
            options={
                'verbose_name': '店員呼び出し',
                'verbose_name_plural': '店員呼び出し',
                'db_table': 'staff_call',
            },
        ),
        migrations.AddField(
            model_name='session',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.store', verbose_name='店舗'),
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.store', verbose_name='店舗'),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=20, verbose_name='テーブル番号')),
                ('qr_code_url', models.CharField(max_length=255, unique=True, verbose_name='QRコードURL')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='定員数')),
                ('is_available', models.BooleanField(default=True, verbose_name='利用可能フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': 'テーブル',
                'verbose_name_plural': 'テーブル',
                'db_table': 'table',
            },
        ),
        migrations.AddField(
            model_name='session',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.table', verbose_name='テーブル'),
        ),
        migrations.CreateModel(
            name='MenuItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('original', 'オリジナル'), ('thumbnail', 'サムネイル'), ('large', '大サイズ')], max_length=20, verbose_name='画像タイプ')),
                ('file_path', models.CharField(max_length=500, verbose_name='ファイルパス')),
                ('file_size', models.IntegerField(help_text='バイト', verbose_name='ファイルサイズ')),
                ('width', models.IntegerField(blank=True, help_text='ピクセル', null=True, verbose_name='画像幅')),
                ('height', models.IntegerField(blank=True, help_text='ピクセル', null=True, verbose_name='画像高さ')),
                ('mime_type', models.CharField(max_length=50, verbose_name='MIMEタイプ')),
                ('uploaded_at', models.DateTimeField(verbose_name='アップロード日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.menuitem', verbose_name='メニュー項目')),
            ],
            options={
                'verbose_name': 'メニュー画像',
                'verbose_name_plural': 'メニュー画像',
                'db_table': 'menu_item_image',
                'indexes': [models.Index(fields=['menu_item', 'image_type'], name='menu_item_i_menu_it_0d5559_idx')],
                'unique_together': {('menu_item', 'image_type')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_name', models.CharField(help_text='スナップショット', max_length=100, verbose_name='商品名')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='スナップショット', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='単価')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='数量')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='小計')),
                ('status', models.CharField(choices=[('pending', '未調理'), ('cooking', '調理中'), ('ready', '調理完了'), ('served', '提供済み'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='ステータス')),
                ('note', models.TextField(blank=True, help_text='アレルギー対応など', null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.menuitem', verbose_name='メニュー項目')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='注文')),
            ],
            options={
                'verbose_name': '注文明細',
                'verbose_name_plural': '注文明細',
                'db_table': 'order_item',
                'indexes': [models.Index(fields=['order'], name='order_item_order_i_08a5da_idx'), models.Index(fields=['status'], name='order_item_status_5ff3d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='合計金額')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', '現金'), ('credit_card', 'クレジットカード'), ('electronic', '電子マネー')], max_length=20, null=True, verbose_name='支払い方法')),
                ('status', models.CharField(choices=[('pending', '会計待ち'), ('paid', '支払済み'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='ステータス')),
                ('requested_at', models.DateTimeField(verbose_name='会計依頼日時')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支払完了日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.session', verbose_name='セッション')),
            ],
            options={
                'verbose_name': '会計',
                'verbose_name_plural': '会計',
                'db_table': 'payment',
                'indexes': [models.Index(fields=['status', 'requested_at'], name='payment_status_0a652e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['session', 'order_number'], name='order_session_836fd1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'ordered_at'], name='order_status_195a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='staffcall',
            index=models.Index(fields=['session', 'status'], name='staff_call_session_56a42e_idx'),
        ),
        migrations.AddIndex(
            model_name='staffcall',
            index=models.Index(fields=['called_at'], name='staff_call_called__2bd339_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['store', 'category', 'display_order'], name='menu_item_store_i_c78b06_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_available', 'is_active'], name='menu_item_is_avai_18e1ba_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['store', 'display_order'], name='category_store_i_82129d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['store', 'role'], name='user_store_i_c2b090_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['store', 'table_number'], name='table_store_i_9cde79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('store', 'table_number')},
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['table', 'status'], name='session_table_i_5c2edc_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['started_at'], name='session_started_cb867d_idx'),
        ),
    ]
